### PR TITLE
Login and LoginOk mostly working.

### PR DESCRIPTION
**Pull request by akirarat**
Working on OwnHomeData now. Cleaned up other messages from CoC that doesn't apply for CR.

### CODE REVIEW

**Comment by ghost** [comment]
Hi! Thanks for expressing your interest! Unfortunately, I won't be maintaining this organization any more, but if you'd like, I could give you the keys and let you take a crack at reversing Clash Royale

**Comment by akirarat** [comment]
Thanks very gracious of you. See if you can transfer ownership by going to Settings > Danger Zone > Transfer ownership and put in my name "akirarat"

**Comment by ghost** [comment]
Would you like access to the whole organization?

**Comment by akirarat** [comment]
Sure, if you are going to transfer royale-proxy over to me.

**Comment by ghost** [comment]
Yup, I'll start the transfer now

**Comment by ghost** [comment]
You've been invited as an owner

**Pull request merged**
